# Generated by Django 5.0.12 on 2025-02-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SUPER ADMIN', 'SUPER_ADMIN'), ('AUCTION MANAGER', 'AUCTION_MANAGER'), ('TEAM MANAGER', 'TEAM_MANAGER')], default='SUPER ADMIN'),
        ),
    ]
