# Generated by Django 5.0.12 on 2025-02-06 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('BATSMAN', 'BATSMAN'), ('BOWLER', 'BOWLER'), ('ALL_ROUNDER', 'ALL_ROUNDER'), ('WICKET_KEEPER', 'WICKET_KEEPER')], max_length=255)),
                ('base_price', models.IntegerField(default=0)),
                ('stats', models.JSONField(default=dict)),
                ('shadow_base_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('budget', models.IntegerField(default=500000000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
