# Generated by Django 5.0.12 on 2025-02-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_players_options_players_created_at_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='category',
            field=models.CharField(choices=[('CATEGORY A', 'CATEGORY A'), ('CATEGORY B', 'CATEGORY B'), ('CATEGORY C', 'CATEGORY C')], default='CATEGORY A', max_length=255),
        ),
    ]
