# Generated by Django 5.0.12 on 2025-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_players_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='category',
            field=models.CharField(choices=[('CATEGORY_A', 'CATEGORY_A'), ('CATEGORY_B', 'CATEGORY_B'), ('CATEGORY_C', 'CATEGORY_C')], default='CATEGORY_A', max_length=255),
        ),
    ]
